// Bootstrap source data; normal authoring edits the JSON files directly.
import {mkdir,writeFile,readFile,copyFile} from 'node:fs/promises';
const out=async(p,x)=>{await mkdir(p.substring(0,p.lastIndexOf('/')),{recursive:true});await writeFile(p,JSON.stringify(x,null,2)+'\n');};
const letters=[...'aeioulmsn'];
await out('data/phonemes.json',letters.map(id=>({id,ipa:id,kind:'aeiou'.includes(id)?'vowel':'consonant',audio:'assets/audio/phonemes/'+id+'.m4a',status:'active'})));
await out('data/graphemes.json',[...letters.map(id=>({id,display:id,phonemes:[id],core:true})),{id:'ó',display:'ó',phonemes:['o'],core:false,requiresAccentSupport:true},{id:'b',display:'b',phonemes:['b'],core:false},{id:'v',display:'v',phonemes:['b'],core:false},{id:'c',display:'c',phonemes:['k','θ'],contextRequired:true,core:false},{id:'z',display:'z',phonemes:['θ'],core:false},{id:'h',display:'h',phonemes:[],core:false},{id:'ch',display:'ch',phonemes:['tʃ'],core:false},{id:'ll',display:'ll',phonemes:['ʝ'],core:false},{id:'y',display:'y',phonemes:['ʝ'],contextRequired:true,core:false},{id:'r',display:'r',phonemes:['ɾ','r'],contextRequired:true,core:false}]);
const syllables=[...letters.slice(0,5),...'lmsn'.split('').flatMap(c=>[...'aeiou'].map(v=>c+v)),...'al el es en un as os ol an'.split(' ')].map((s,i)=>({id:'sy-'+s,string:s,word:s,displayUpper:s.toUpperCase(),phonemes:[...s],graphemes:[...s],phonemeCount:s.length,structure:[...s].map(c=>'aeiou'.includes(c)?'V':'C').join(''),requiredLetters:[...new Set(s)],priority:i<5?2:1,frequency:'common',difficulty:s.length===1?1:2,recommended:true,interleave:true,writing:true,reading:true,kind:'syllable'}));
await out('data/syllables-v1.json',syllables);
const names='sol sal ala ola oso osa lana luna mano mesa mula mono asa uno masa suma limón melón molino'.split(' ');
const word=(s,i)=>{const p=[...s.normalize('NFD').replace(/[\u0300-\u036f]/g,'')];return {id:s.normalize('NFD').replace(/[\u0300-\u036f]/g,''),word:s,displayUpper:s.toUpperCase(),phonemes:p,graphemes:[...s],phonemeCount:p.length,syllableCount:p.filter(x=>'aeiou'.includes(x)).length,structure:p.map(x=>'aeiou'.includes(x)?'V':'C').join(''),initialPhoneme:p[0],finalPhoneme:p[p.length-1],phonemePositions:Object.fromEntries([...new Set(p)].map(x=>[x,p.flatMap((v,j)=>v===x?[j]:[])])),requiredLetters:[...new Set([...s])],oral:true,reading:true,writing:true,requiresAccentSupport:s.includes('ó'),segmentation:true,blending:true,imageRequired:true,imageClarity:['osa','asa','mula'].includes(s)?'review':'high',image:['osa','asa','mula'].includes(s)?null:'assets/pictograms/'+s.normalize('NFD').replace(/[\u0300-\u036f]/g,'')+'.png',reviewRequired:['osa','asa','mula'].includes(s),difficulty:i<12?1:i<16?2:3,priority:i<12?1:i<16?2:3,wordAudio:null,wordAudioRequired:false,meaning:s==='masa'?'masa de pan cruda':s==='mono'?'animal':s,kind:'word'};};
await out('data/words-v1.json',names.map(word));
const nube=word('nube',20);nube.reading=false;nube.writing=false;nube.segmentation=false;nube.blending=false;nube.difficulty=1;
await out('data/oral-bank-v1.json',[nube]);
await out('data/relations.json',{nearPairs:[['sol','sal'],['ola','ala'],['oso','osa'],['osa','asa'],['mesa','masa'],['lana','luna'],['limon','melon']],changes:[['mesa','masa'],['lana','luna'],['sol','sal'],['ola','ala']],additions:[{from:'ala',to:'sala',phonemesFrom:['a','l','a'],phonemesTo:['s','a','l','a'],added:'s',note:'SALA solo en comparación avanzada; fuera del núcleo inicial.'}],manipulations:[{operation:'substitute',from:'mesa',to:'masa',index:1,phoneme:'a'},{operation:'substitute',from:'lana',to:'luna',index:1,phoneme:'u'}]});
// Version declarations are maintained independently of content bootstrapping.
// Audio always comes from the final sources, including after bootstrapping.
const {syncAudio}=await import('./sync-audio.mjs');
await syncAudio();
